baseURL = 'https://til.moonlab.top/'
languageCode = 'zh-CN'
title = 'MoonLab - TIL'
theme = 'sim'

summaryLength = '50'
hasCJKLanguage = true

[pagination]
  disableAliases = false
  pagerSize = 7
  path = 'page'

